<?php
session_start();
if (!isset($menuAccess[$s]["add"]) || !isset($menuAccess[$s]["edit"])) {
  header("Location: " . str_replace("popup", "index", preg_replace("/&id=\d+/", "", preg_replace("/&mode=\w+/", "", $_SERVER["REQUEST_URI"]))));
}

$empc = new EmpRmb();
if (isset($_POST["btnSimpan"])) {
  $empc = $empc->processForm();
  $loc = str_replace("popup", "index", preg_replace("/&id=\d+/", "", preg_replace("/&mode=\w+/", "", $_SERVER["REQUEST_URI"])));
  $_SESSION["entity_id"] = "";
//  header("Location: " . $loc);
  echo "<script>window.parent.location='$loc';</script>";
  die();
}
$empc->id = $_GET["id"];
$empc = $empc->getById();
$_SESSION["entity_id"] = $empc->id;

$cutil = new Common();
$ui = new UIHelper();
$disabled = "disabled=disabled";
if (isset($menuAccess[$s]["add"]) || isset($menuAccess[$s]["edit"])) {
  $disabled = "";
}
$__validate["formid"] = "myForm";
$__validate["items"] = array(
//    "rmbNo" => array("rule" => "required", "msg" => "Field Nomor Sertifikat harus diisi.."),
//    "rmbCat" => array("rule" => "required", "msg" => "Field Kategori harus diisi.."),
    "rmbType" => array("rule" => "required", "msg" => "Field Tipe harus diisi.."),
    "rmbVal" => array("rule" => "required", "msg" => "Field Nilai harus diisi.."),
    "rmbDate" => array("rule" => "required", "msg" => "Field Tanngal harus diisi.."),
//    "rmbDateStart" => array("rule" => "required", "msg" => "Field Tanggal Mulai harus diisi.."),
//    "rmbDateEnd" => array("rule" => "required", "msg" => "Field Tanggal Akhir harus diisi.."),
);

require_once HOME_DIR . "/tmpl/__header__.php";
?>

<div class="centercontent contentpopup">
  <div class="pageheader">
    <h1 class="pagetitle"><?php echo $arrTitle[getField("select kodeInduk from app_menu where kodeMenu='$s'")] . " - " . $arrTitle[$s] ?></h1>
    <?= getBread(ucwords($mode . " data")) ?>
    <span class="pagedesc">&nbsp;</span>

    <?php include './tmpl/__emp_header__.php'; ?>
    <div id="contentwrapper" class="contentwrapper">
      <form action="<?php echo preg_replace("/&id=\d+/", "", preg_replace("/&modedf=\w+/", "", $_SERVER["REQUEST_URI"])) ?>" method="post" id="myForm" class="stdform" enctype="multipart/form-data">
        <br class="clear" />

        <div class="pos_r_button_popup">
          <p class="stdformbutton">
            <input type="submit" class="submit radius2 btn_save" id="btnSimpan" name="btnSimpan" value="Simpan"/>&nbsp;
            <input type="button" class="cancel radius2 btn_back" value="Cancel" onclick="closeBox();"/>
          </p>
        </div>
        <ul class="hornav">
          <li class="current"><a href="#tab_data">Data</a></li>
          <li><a href="#tab_files">Files/Documents</a></li>
        </ul>
        <div id="tab_data" class="subcontent" style="margin-top: 0">
          <table style="width: 100%">
            <tr>
              <td style="width:50%">
                <p id="p0">
                  <label>Nomor </label>
                  <span class="fieldB" style="font-size: 12px; display: inline-block;padding: 2px 30px 5px 0; overflow:hidden;">&nbsp;&nbsp;<?= $empc->rmbNo == "" ? "<b>AUTO GENERATED by System</b>" : $empc->rmbNo ?></span>
				  <input type="hidden" id="rmbJenis" name="rmbJenis" value="<?php echo $arrParam[$s];?>">
                </p>
              </td>
              <td style="width:50%">
                <p id="p0">
                  <label>Balance </label>
                  <span style="display: inline-block; width: 40%" class="mnuma" id="currBal">&nbsp;</span>
                </p>
              </td>
            </tr>
            <tr>
              <td>
                <p id="p0">
                  <label class="l-input-small">Tipe</label>
                  <span class="fieldB">
                    <?php
					
                    $sql = $arrParam[$s] == "m" ?
					"select kodeData id, namaData description from mst_data where statusData='t' and kodeCategory='".$arrParameter[18]."' order by urutanData":
					"select kodeData id, namaData description from mst_data  where statusData='t' and kodeCategory='E19' order by urutanData";
                    echo $cutil->generateSelectWithEmptyOption($sql, "id", "description", "rmbType", $empc->rmbType, "", " $disabled class='single-deselect-td'");
                    ?>
                  </span>
                </p>
              </td>
              <td>
                <p id="p0">
                  <label>Limit</label>
                  <span style="display: inline-block; width: 40%" class="mnuma" id="limitBal">
				  
				  <?php
					$plafon = $arrParam[$s] == "m" ? "kacamata" : "kesehatan";
					echo getField("select sum(t1.plafon_value) from emp_plafon t1 join mst_data t2 on (t1.plafon_id=t2.kodeData) where t1.parent_id='".$_SESSION["curr_emp_id"]."' and lower(t2.namaData) like '%".$plafon."%'");
				  ?>
				  
				  </span>
                </p>
              </td>
            </tr>
			
            <tr>
              <td>
                <p><?= $ui->createLabelSpanInputAttr("Nilai", $empc->rmbVal, "rmbVal", "rmbVal", "smallinput mnum mnuma", "") ?></p>
                <p id="p0"><?= $ui->createLabelSpanInputAttr("Keterangan", $empc->remark, "remark", "remark", "mediuminput", "") ?></p>
              </td>
              <td>
                <p id="p0"><?= $ui->createLabelSpanInputAttr("Tanggal", $empc->rmbDate == "" ? date("Y-m-d") : $empc->rmbDate, "rmbDate", "rmbDate", "hasDatePicker2", "", "") ?></p>
				
                <p id="p0" style="display:<?php echo $arrParam[$s] == "m" ? "none" : "block"; ?>" >
                  <label class="l-input-small">Kategori</label>
                  <span class="fieldB">
                    <?php
                    $sql = "select kodeData id, namaData description, kodeInduk from mst_data  where kodeCategory='E20' order by kodeInduk,urutanData";
                    echo $cutil->generateRadio($sql, "id", "description", "rmbCat", $empc->rmbCat);
                    ?>
                  </span>
                </p>
				
              </td>
            </tr>
          </table>
          <table id="inapOnly" style="width: 100%;display: none">
            <tr>
              <td style="width:50%">
                &nbsp;
              </td>
              <td style="width:50%">
                <p >
                  <label class="l-input-small">Periode</label>
                  <input type="text" value="<?= $empc->rmbDateStart ?>" class="hasDatePicker2" name="rmbDateStart" id="rmbDateStart">&nbsp;&nbsp;
                  <input type="text" value="<?= $empc->rmbDateEnd ?>" class="hasDatePicker2" name="rmbDateEnd" id="rmbDateEnd">&nbsp;&nbsp;
                </p>
              </td>
            </tr>
          </table>
        </div>        
        <div id="tab_files" class="subcontent" style="margin-top: 0; display: none">
          <div id='pos_r'>
            <a id="btnAddFile" href="#addfile" class="btn btn1 btn_link new"><span>Tambah File</span></a>
          </div>
          <table cellpadding="0" cellspacing="0" border="0" class="stdtable stdtablequick" id="dtFile">
            <thead>
              <tr>
                <th>Deskripsi</th>
                <th width="100px">File</th>
                <th width="100px">Date</th>
                <th width="80px">Download</th>
                <th width="40px">&nbsp;</th>
              </tr>
            </thead>
            <tbody>

              <?php
              $fq = new EmpRmbFiles();
              $fq->parentId = $empc->id;
              $dFiles = $fq->getByParentId();
              if (count($dFiles) > 0) {
                $dcount = 1;
                foreach ($dFiles as $df) {
                  echo "<tr>";
                  echo "<input type='hidden' id='dfrow_$dcount'/>  <input type=\"hidden\" id=\"dfId_$dcount\" name=\"dfId[]\" value=\"$df->id\" />"; // NO
                  echo "<td ><input type='text' id=\"dfDesc_$dcount\" name=\"dfDesc[]\" value=\"$df->description\"/></td>"; // desc
                  echo "<td width=\"100px\"><input type=\"file\" id=\"dfFile_$dcount\" name=\"dfFile[]\"></td>"; // file
                  echo "<td width=\"100px\">" . ($df->updDate == NULL ? substr($df->creDate, 0, 10) : substr($df->updDate, 0, 10)) . "</td>"; // date
                  if ($df->filename != "") {
                    echo "<td width=\"80px\"><a href=\"download.php?d=emprmb&f=" . $df->id . "\"><img src=\"" . getIcon($df->filename) . "\" align=\"center\" style=\"vertical-align:middle\" ></a></td>"; // file
                  } else {
                    echo "<td width=\"80px\">&nbsp;No File Uploaded</td>";
                  }
                  echo "<td><a id='delf_$dcount'  href='#deleteFile' class='delete delRow' onclick=\"if(confirm('Are you sure to delete ?')) {jQuery(this).parent().parent().remove();}\" ></a></td>";
                  echo "</tr>";
                  $dcount++;
                }
              }
              ?>
            </tbody>
          </table>
        </div>
    </div>

    <script type="text/javascript">
      jQuery(document).ready(function () {
        jQuery("#myForm").validate().settings.ignore = [];

        jQuery(".hasDatePicker2").datepicker({
          dateFormat: "yy-mm-dd"
        });
        jQuery("#rmbYear").mask("9999");
        jQuery('.single-deselect-td').chosen({allow_single_deselect: true, width: '60%', search_contains: true});
        jQuery('.single-deselect-40').chosen({allow_single_deselect: true, width: '40%', search_contains: true});
        jQuery('.single-deselect').chosen({allow_single_deselect: true, width: '90%', search_contains: true});

        jQuery(".mnuma").each(function () {
          jQuery(this).css("text-align", "right");
          jQuery(this).autoNumeric("init", {wEmpty: 'zero', mDec: 0, vMin: 0, vMax: 9999999999999999999999999999});
        });
        jQuery('input[type=radio][name=rmbCat]').trigger("change");
        jQuery('input[type=radio][name=rmbCat]').change(function () {
          if (this.value === "611") {
            jQuery("#inapOnly").show();
          }
          else {
            jQuery("#rmbDateEnd").val("");
            jQuery("#rmbDateStart").val("");
            jQuery("#inapOnly").hide();
          }
        });
        _fileHandlers();
        jQuery("#myForm").submit(function (event) {
          if (jQuery("#myForm").valid()) {
            clearFormat();
            return true;
          } else {
            event.preventDefault();
            return false;
          }
        });
      });

      function _fileHandlers() {
        jQuery("#btnAddFile").click(function (e) {
          var tblRow = 0;
          if (jQuery("#dtFile tbody tr:last").length > 0) {
            var maxNum = 0;
            jQuery("#dtFile tbody input[id^='dfrow_']").each(function () {
              var num = parseInt(jQuery(this).attr("id").split("_")[1]);
              if (num > maxNum) {
                maxNum = num;
              }
            });
            tblRow = maxNum;
          }
          tblRow++;
          var r0 = '<input type="hidden" id="dfrow_' + tblRow + '" value="' + tblRow + '" /><input type="hidden" id="dfId_' + tblRow + '" name="dfId[]" value="" />';
          r0 += '<td><input type="text" id="dfDesc_' + tblRow + '" name="dfDesc[]" value=""/></td>'; //desc
          r0 += '<td width=\"100px\"><input type="file" id="dfFile_' + tblRow + '" name="dfFile[]"></td>'; //file
          r0 += '<td width=\"100px\">&nbsp;</td>'; //date
          r0 += '<td width=\"80px\">&nbsp;</td>'; //download
          r0 += "<td><a id='delf_" + tblRow + "'  href='#deleteFile' class='delete delRow' onclick=\"if(confirm('Are you sure to delete ?')){jQuery(this).parent().parent().remove();}\" ></a></td>";
          jQuery("#dtFile tbody").append('<tr>' + r0 + '</tr>');
          jQuery("#dfDesc_" + tblRow).focus(30);
        });
      }
      
      function clearFormat() {
        jQuery(".mnum").each(function (index) {
          var id = jQuery(this).attr('id');
          var c = jQuery("#" + id).autoNumeric('get');
          jQuery("#" + id).autoNumeric('destroy');
          jQuery("#" + id).val(c);
        });
        jQuery(".mnumd").each(function (index) {
          var id = jQuery(this).attr('id');
          var c = jQuery("#" + id).autoNumeric('get');
          jQuery("#" + id).autoNumeric('destroy');
          jQuery("#" + id).val(c);
        });
      }
      
    </script>

